name: food_delivery_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # HIVE Packages for OFFLINE Storage
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  path_provider: ^2.1.1

  # BLoC Packages for State Management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  # HTTP Package for API Integration
  http: ^1.1.0
  http_parser: ^4.0.2
  flutter_dotenv: ^5.1.0

  # For date formatting
  intl: ^0.18.1

  # For internet connectivity
  connectivity_plus: ^5.0.2

  # Used to display Recipe Categories in HomePage.
  carousel_slider: ^4.2.1

  # Used to display summary of a recipe on Recipe Details Screen

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/keys/api_key.env
    - asset/splash.jpg
    - asset/recipe_categories/
    

  # fonts:
  #   - family: Manrope
  #     fonts:
  #       - asset: assets/font/static/Manrope-Bold.ttf
  #       - asset: assets/font/static/Manrope-ExtraBold.ttf
  #       - asset: assets/font/static/Manrope-ExtraLight.ttf
  #       - asset: assets/font/static/Manrope-Light.ttf
  #       - asset: assets/font/static/Manrope-Medium.ttf
  #       - asset: assets/font/static/Manrope-Regular.ttf
  #       - asset: assets/font/static/Manrope-SemiBold.ttf

